
import config

# [ref config_viewport] 

ficcontent_header = f"""
;; Autogenerated file. Do not modify by hand.
;; Use script clearVertColBuf.py
;; [ref config_viewport] 
#include "config.h"
#ifndef  USE_C_VERTCOLBUF
_initVertCol

"""	


ficcontent_trailer = f"""

initVertColDone    
	rts

#endif // USE_C_VERTCOLBUF
"""

def main ():
    
	content = ficcontent_header
    # Generate Sky part of viewport
	content += f"patch_red_in_sky_part:lda #$40	; pixel eteint\n"
	for ii in range (0, (config.VIEWPORT_HEIGHT * 3)//2, 3):
		content += f"sta _bufVertCol+{ii}\n"
	content += f"patch_green_in_sky_part:lda #$40	; pixel eteint\n"
	for ii in range (0, (config.VIEWPORT_HEIGHT * 3)//2, 3):
		content += f"sta _bufVertCol+{ii+1}\n"
	content += f"patch_blue_in_sky_part:lda #$7F	; pixel allume\n"
	for ii in range (0, (config.VIEWPORT_HEIGHT * 3)//2, 3):
		content += f"sta _bufVertCol+{ii+2}\n"

	# Generate Ground part of viewport
	content += f"patch_red_on_ground_part:lda #$40	; pixel eteint\n"
	for ii in range ((config.VIEWPORT_HEIGHT * 3)//2, (config.VIEWPORT_HEIGHT * 3), 3):
		content += f"sta _bufVertCol+{ii}\n"
	content += f"patch_green_on_ground_part:lda #$7F	; pixel allume\n"
	for ii in range ((config.VIEWPORT_HEIGHT * 3)//2, (config.VIEWPORT_HEIGHT * 3), 3):
		content += f"sta _bufVertCol+{ii+1}\n"
	content += f"patch_blue_on_ground_part:lda #$40	; pixel eteint\n"
	for ii in range ((config.VIEWPORT_HEIGHT * 3)//2, (config.VIEWPORT_HEIGHT * 3), 3):
		content += f"sta _bufVertCol+{ii+2}\n"
	content += ficcontent_trailer
	print (content)

if __name__ == "__main__":
    main()

