
import config

# [ref config_viewport] 

ficcontent_header = f"""
;; Autogenerated file. Do not modify by hand.
;; Use script clearVertColBuf.py
;; [ref config_viewport] 
#include "config.h"
#ifndef  USE_C_VERTCOLBUF
_initBufVertCol

"""	


ficcontent_trailer = f"""

initBufVertColDone    
	rts

#endif // USE_C_VERTCOLBUF
"""

def main ():
    
	content = ficcontent_header
    # Generate Sky part of viewport
	content += f"patch_sky_color:lda #21	; Blue Sky\n"
	for ii in range (0, config.VIEWPORT_HEIGHT//2):
		content += f"sta _bufVertColRight+{ii}\n"
		content += f"sta _bufVertColLeft+{ii}\n"

	# Generate Ground part of viewport
	content += f"patch_ground_color:lda #42	; Green Grass Ground\n"
	for ii in range (config.VIEWPORT_HEIGHT//2, config.VIEWPORT_HEIGHT):
		content += f"sta _bufVertColRight+{ii}\n"
		content += f"sta _bufVertColLeft+{ii}\n"

	content += ficcontent_trailer
	print (content)

if __name__ == "__main__":
    main()

