
import config

# [ref config_viewport] 

ficcontent_header = f"""
;; Autogenerated file. Do not modify by hand.
;; Use script clearColumn.py
;; [ref config_viewport] 
#include "config.h"
#ifndef  USE_C_VIEWPORT
_clearColumn
.(
    lda _idxScreenCol
    lsr
    tax 
"""	


ficcontent_trailer = f"""

clearColumnDone    
.)
	rts
#endif // USE_C_VIEWPORT
"""

def main ():
    
	content = ficcontent_header

    # Generate Sky part of viewport
	content += f"lda #$40	; pixel eteint\n"
	for ii in range (0, (config.VIEWPORT_HEIGHT * 3)//2, 3):
		content += f"sta HIRES_SCREEN_ADDRESS + VIEWPORT_START_COLUMN/2 + NEXT_SCANLINE_INCREMENT * ( VIEWPORT_START_LINE*3 + {ii}),x\n"
		content += f"sta HIRES_SCREEN_ADDRESS + VIEWPORT_START_COLUMN/2 + NEXT_SCANLINE_INCREMENT * ( VIEWPORT_START_LINE*3 + {ii+1}),x\n"

	content += f"lda #$7F	; pixel allume\n"
	for ii in range (0, (config.VIEWPORT_HEIGHT * 3)//2, 3):
		content += f"sta HIRES_SCREEN_ADDRESS + VIEWPORT_START_COLUMN/2 + NEXT_SCANLINE_INCREMENT * ( VIEWPORT_START_LINE*3 + {ii+2}),x\n"

	# Generate Ground part of viewport
	content += f"lda #$40	; pixel eteint\n"
	for ii in range ((config.VIEWPORT_HEIGHT * 3)//2, (config.VIEWPORT_HEIGHT * 3), 3):
		content += f"sta HIRES_SCREEN_ADDRESS + VIEWPORT_START_COLUMN/2 + NEXT_SCANLINE_INCREMENT * ( VIEWPORT_START_LINE*3 + {ii}),x\n"
		content += f"sta HIRES_SCREEN_ADDRESS + VIEWPORT_START_COLUMN/2 + NEXT_SCANLINE_INCREMENT * ( VIEWPORT_START_LINE*3 + {ii+2}),x\n"

	content += f"lda #$7F	; pixel allume\n"
	for ii in range ((config.VIEWPORT_HEIGHT * 3)//2, (config.VIEWPORT_HEIGHT * 3), 3):
		content += f"sta HIRES_SCREEN_ADDRESS + VIEWPORT_START_COLUMN/2 + NEXT_SCANLINE_INCREMENT * ( VIEWPORT_START_LINE*3 + {ii+1}),x\n"

	content += ficcontent_trailer
	print (content)

if __name__ == "__main__":
    main()

