
import config

# [ref config_viewport] 

ficcontent_header = f"""
;; Autogenerated file. Do not modify by hand.
;; Use script copyVertColBuf.py
;; [ref config_viewport] 
#include "config.h"
#ifndef  USE_C_VERTCOLBUF
_copyVertCol
    lda _idxScreenCol
    lsr
    tax 
"""	


ficcontent_trailer = f"""

copyVertColDone    

	rts
#endif // USE_C_VERTCOLBUF
"""

def main ():
    
	content = ficcontent_header


# lda _bufVertCol+0
# sta HIRES_SCREEN_ADDRESS + 1 + NEXT_SCANLINE_INCREMENT * ( VIEWPORT_START_LINE*3 + 0),x     
	for ii in range (0, config.VIEWPORT_HEIGHT * 3, 1):
		content += f"lda _bufVertCol+{ii}\n"
		content += f"sta HIRES_SCREEN_ADDRESS + 1 + NEXT_SCANLINE_INCREMENT * ( VIEWPORT_START_LINE*3 + {ii}),x\n"

	content += ficcontent_trailer
	print (content)

if __name__ == "__main__":
    main()

